import Link from 'next/link'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Link href='/' style={{marginRight: '1rem'}}>Home</Link>
          <Link href='/jira' style={{marginRight: '1rem'}}>Jira</Link>
          <Link href='/dashboard' style={{marginRight: '1rem'}}>Dashboard</Link>
          <Link href='/profile' style={{marginRight: '1rem'}}>Profile</Link>
          <Link href='/screens' style={{marginRight: '1rem'}}>Screens</Link>
          <Link href='/users' style={{marginRight: '1rem'}}>Users</Link>
        </header>
        <hr/>
        {children}
      </body>
    </html>
  )
}
